Repository KNU-HAEDAL/ZZANSUNI_FE, pull requests merged in 2024-09, with the labels that each got.

#106 로그인 기능 수정
  src/apis/ApiResponse.ts
  src/apis/AxiosClient.ts
  src/apis/auth/auth.api.ts
  src/components/features/layout/top-bar/main.tsx
  src/pages/login/components/email/index.tsx
  src/pages/login/index.tsx
  src/pages/login/styles.ts
Labels: 😡 BugFix, ✨ Feature, 📬 API, 💄Design

#112 fix(tab): 탭 선택 이벤트핸들러의 파라미터 수정 (마우스이벤트 e 삭제)
  src/components/common/tab/index.tsx
  src/pages/challenge-detail/index.tsx
Labels: 😡 BugFix

#114 카카오 로그인 기능 구현
  src/apis/auth/social-login.api.ts
  src/pages/login/components/redirect/index.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 📬 API

#115 챌린지 디테일 페이지 설명 탭
  src/apis/challenge-detail/challenge.detail.response.ts
  src/pages/challenge-detail/components/challenge/index.tsx
  src/pages/challenge-detail/components/challenge/styles.ts
  src/pages/challenge-detail/description/index.tsx
  src/pages/challenge-detail/description/styles.ts
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/styles.ts
Labels: ✨ Feature, 💄Design

#118 Fix/issue #116
  src/apis/challenge-detail/challenge.detail.api.ts
  src/apis/challenge-detail/challenge.ranking.api.ts
  src/pages/challenge-detail/components/challenge/styles.ts
  src/pages/challenge-detail/components/user-item/index.tsx
  src/pages/challenge-detail/components/user-item/styles.ts
  src/pages/challenge-detail/description/index.tsx
  src/pages/challenge-detail/description/styles.ts
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/ranking/index.tsx
  src/pages/challenge-detail/ranking/styles.ts
  src/pages/challenge-detail/styles.ts
Labels: 😡 BugFix, 📬 API, 💄Design

#120 리뷰 페이지 엔드포인트, 컴포넌트명 바꾸기 #119
  src/pages/challenge-detail/review-section/index.tsx
  src/pages/review/components/review-item/index.tsx
  src/pages/review/components/review-rating/index.tsx
  src/pages/review/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ♻️ Refactoring

#122 Fix/issue #117
  src/apis/challenge-detail/challenge.ranking.response.ts
  src/apis/review/review.api.ts
  src/apis/review/review.response.ts
  src/components/common/star-rating/index.tsx
  src/pages/challenge-detail/components/ranking-item/index.tsx
  src/pages/challenge-detail/components/ranking-item/styles.ts
  src/pages/challenge-detail/components/user-item/index.tsx
  src/pages/challenge-detail/description-section/index.tsx
  src/pages/challenge-detail/description-section/styles.ts
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/ranking-section/index.tsx
  src/pages/challenge-detail/ranking-section/styles.ts
  src/pages/challenge-detail/ranking/index.tsx
  src/pages/challenge-detail/ranking/styles.ts
  src/pages/challenge-detail/review-section/index.tsx
  src/pages/challenge-detail/review-section/styles.ts
  src/pages/review-list/components/review-item/index.tsx
  src/pages/review-list/components/review-rating/index.tsx
  src/pages/review-list/index.tsx
  src/pages/review/components/review-item/index.tsx
  src/pages/review/components/review-rating/index.tsx
  src/pages/review/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/baseStyles.ts
Labels: 😡 BugFix, ✨ Feature, 📬 API, ♻️ Refactoring

#124 baseStyles horizontal line, vertical line 수정 #123
  src/pages/review/components/review-rating/index.tsx
  src/styles/baseStyles.ts
Labels: 💄Design, ♻️ Refactoring

#126 리뷰 페이지 상하좌우 여백 조정 #125
  src/pages/review/components/review-rating/index.tsx
  src/pages/review/index.tsx
Labels: 💄Design

#128 챌린지 상세 페이지 랭킹 섹션 무한 스크롤 고치기 #121
  src/apis/challenge-detail/challenge.ranking.api.ts
  src/apis/challenge-detail/challenge.ranking.response.ts
  src/apis/review/review.response.ts
  src/pages/challenge-detail/components/ranking-item/styles.ts
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/ranking-section/index.tsx
  src/pages/review/index.tsx
Labels: 😡 BugFix, 📬 API, 💄Design

#131 챌린지 상세, 리뷰 엔드포인트 수정 & 챌린지 참여 버튼 이벤트 구현 #127
  src/apis/challenge-detail/challenge.detail.api.ts
  src/pages/challenge-detail/components/challenge/index.tsx
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/review-section/index.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 📬 API

#133 로그인 관련 UX 개선 #132
  src/pages/login/components/email/index.tsx
  src/pages/login/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/routes/protected-route.tsx
Labels: ✨ Feature, 📬 API, ♻️ Refactoring

#134 헤더를 페이지 상단에 고정시키기 #129
  src/components/features/layout/top-bar/index.tsx
  src/components/features/layout/top-bar/main-bar.tsx
  src/components/features/layout/top-bar/page-bar.tsx
  src/pages/main/index.tsx
Labels: ✨ Feature

#142 탭 컴포넌트 디자인 변경 #141
  src/components/common/tab/index.tsx
  src/components/common/tab/styles.ts
  src/components/common/tabs/index.tsx
  src/components/common/tabs/styles.ts
  src/components/common/tabs/tap-panels.tsx
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/styles.ts
  src/pages/challenge-record/index.tsx
Labels: 💄Design, ♻️ Refactoring

#149 리뷰 쓰기 페이지 #144
  src/apis/review/review.api.ts
  src/apis/review/review.response.ts
  src/components/common/star-rating/index.tsx
  src/pages/review-write/index.tsx
  src/pages/review/components/review-rating/index.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 📦 Environment, 📬 API, 💄Design

#152 리뷰 아이템에 날짜 및 다른 정보 표시되도록 하기 #145
  src/apis/review/review.response.ts
  src/pages/review/components/review-item/index.tsx
Labels: ✨ Feature, 💄Design, ♻️ Refactoring

#154 스트링 포맷팅 함수들 모듈화 (formatters) #153
  src/pages/challenge-detail/description-section/index.tsx
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-detail/review-section/index.tsx
  src/pages/review-write/index.tsx
  src/pages/review/components/review-item/index.tsx
  src/pages/review/components/review-rating/index.tsx
  src/utils/formatters.ts
Labels: ♻️ Refactoring

#160 챌린지 list 페이지 구현
  .github/workflow/ci.yml
  src/apis/challenge-list/getChallengeList.api.ts
  src/apis/challenge-list/getChallengeList.response.ts
  src/pages/challenge-list/components/contents/index.tsx
  src/pages/challenge-list/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: ✨ Feature, 📬 API

#164 레이아웃 전체적으로 수정 #146
  src/components/features/layout/nav-bar-layout/index.tsx
  src/components/features/layout/nav-bar/buttons.tsx
  src/components/features/layout/nav-bar/index.tsx
  src/pages/challenge-detail/index.tsx
  src/pages/main/index.tsx
  src/pages/my-challenge/index.tsx
  src/pages/review-write/index.tsx
  src/pages/review/index.tsx
  src/routes/index.tsx
  src/styles/globalStyles.ts
  src/styles/reset.css
Labels: 😡 BugFix, 💄Design, ♻️ Refactoring

#166 CTA 버튼, textarea 리팩토링 & 모듈화 #165
  src/components/common/cta/index.tsx
  src/components/common/form/textarea/index.tsx
  src/pages/challenge-detail/components/challenge-item/index.tsx
  src/pages/challenge-detail/components/challenge-item/styles.ts
  src/pages/review-write/index.tsx
Labels: ♻️ Refactoring

#167 내 챌린지 기록 리스트 보기 페이지 수정
  src/apis/my-challenge-record/getReview.api.ts
  src/apis/my-challenge-record/getReview.response.ts
  src/pages/my-challenge-record/components/list-item.tsx
  src/pages/my-challenge-record/index.tsx
Labels: ✨ Feature, 📬 API, ♻️ Refactoring

#171 메인페이지 기능 수정
  src/apis/challenge-record/challenge.record.api.ts
  src/pages/challenge-list/index.tsx
  src/pages/challenge-record/index.tsx
  src/pages/main/components/category/index.tsx
  src/pages/main/components/tier/index.tsx
  src/pages/main/components/tier/styles.ts
  src/styles/baseStyles.ts
Labels: 😡 BugFix, ✨ Feature, 🔧 Chore, 💄Design

#173 챌린지 상세보기 페이지 이동 기능 구현
  src/apis/challenge-record/challenge.record.api.ts
  src/pages/challenge-list/components/contents/index.tsx
  src/pages/challenge-list/index.tsx
  src/pages/shorts/components/info/index.tsx
  src/pages/shorts/index.tsx
Labels: 😡 BugFix, ✨ Feature, 📬 API

#178 shorts UI 수정
  package.json
  src/assets/shorts/shorts-img.png
  src/pages/shorts/components/contents/index.tsx
  src/pages/shorts/components/image/index.tsx
  src/pages/shorts/components/info/category-icons.tsx
  src/pages/shorts/components/info/index.tsx
  src/pages/shorts/index.tsx
  src/routes/index.tsx
Labels: 😡 BugFix, 💄Design

#179 챌린지 인증/기록 페이지 #148
  src/apis/challenge-record/challenge.record.api.ts
  src/apis/challenge-record/challenge.record.response.ts
  src/assets/stamp-active.svg
  src/assets/stamp-inactive.svg
  src/components/common/challenge-title/index.tsx
  src/components/common/cta/index.tsx
  src/components/common/form/textarea/index.tsx
  src/components/common/tabs/tab-panels/index.tsx
  src/components/features/layout/top-bar/page-bar.tsx
  src/pages/challenge-detail/index.tsx
  src/pages/challenge-record/components/bottom-sheet/index.tsx
  src/pages/challenge-record/components/caution/index.tsx
  src/pages/challenge-record/components/record-item/index.tsx
  src/pages/challenge-record/components/stamp-board/index.tsx
  src/pages/challenge-record/components/stamp/index.tsx
  src/pages/challenge-record/components/verification/index.tsx
  src/pages/challenge-record/index.tsx
  src/pages/challenge-record/records/index.tsx
  src/pages/challenge-record/verification/index.tsx
  src/pages/review-write/index.tsx
  src/pages/review/index.tsx
  src/routes/index.tsx
Labels: ✨ Feature, 📬 API, ♻️ Refactoring
